name: base                                                                   
channels:                                                                    
- defaults
- conda-forge
dependencies:
  - python=3.6
  - pandas=0.22.0
  - sqlalchemy=1.2.1
  - scikit-learn=0.20.0
  - pyodbc=4.0.23
  - jupyterlab
  - beakerx
